/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Add;

import App.App;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Ardenshley Nage
 */
public class Add_view extends javax.swing.JFrame {

    private static Add_ctrl controller;
    private static final String HOST = "jdbc:mysql://localhost:3306/contact_manager";
    private static final String USER = "root";
    private static final String PASSWORD = "";

    /**
     * Creates new form Add_view
     */
    public Add_view() {
        initComponents();
        controller = new Add_ctrl(HOST, USER, PASSWORD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        last_name = new javax.swing.JLabel();
        first_name = new javax.swing.JLabel();
        phone_number = new javax.swing.JLabel();
        mail_user = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        back_menu = new javax.swing.JButton();
        add_valid1 = new javax.swing.JButton();
        ExitApp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ajouter un contact");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ajoutez un nouveau contact");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));

        last_name.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        last_name.setForeground(new java.awt.Color(255, 255, 255));
        last_name.setText("Nom          :");

        first_name.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        first_name.setForeground(new java.awt.Color(255, 255, 255));
        first_name.setText("Prénom      :");

        phone_number.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        phone_number.setForeground(new java.awt.Color(255, 255, 255));
        phone_number.setText("Téléphone  :");

        mail_user.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        mail_user.setForeground(new java.awt.Color(255, 255, 255));
        mail_user.setText("E-mail        :");

        back_menu.setBackground(new java.awt.Color(0, 0, 0));
        back_menu.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        back_menu.setForeground(new java.awt.Color(255, 255, 255));
        back_menu.setText("Retour");
        back_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_menuActionPerformed(evt);
            }
        });
        back_menu.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                back_menu.setBackground(Color.WHITE);
                back_menu.setForeground(Color.BLACK);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                back_menu.setBackground(Color.BLACK);
                back_menu.setForeground(Color.WHITE);
            }
        });

        add_valid1.setBackground(new java.awt.Color(0, 0, 0));
        add_valid1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        add_valid1.setForeground(new java.awt.Color(255, 255, 255));
        add_valid1.setText("Ajouter");
        add_valid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_valid1ActionPerformed(evt);
            }
        });
        add_valid1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                add_valid1.setBackground(Color.WHITE);
                add_valid1.setForeground(Color.BLACK);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                add_valid1.setBackground(Color.BLACK);
                add_valid1.setForeground(Color.WHITE);
            }
        });

        ExitApp.setBackground(new java.awt.Color(0, 0, 0));
        ExitApp.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ExitApp.setForeground(new java.awt.Color(255, 255, 255));
        ExitApp.setText("Quitter");
        ExitApp.setMaximumSize(new java.awt.Dimension(78, 33));
        ExitApp.setMinimumSize(new java.awt.Dimension(78, 33));
        ExitApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitAppActionPerformed(evt);
            }
        });
        ExitApp.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                ExitApp.setBackground(Color.WHITE);
                ExitApp.setForeground(Color.BLACK);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                ExitApp.setBackground(Color.BLACK);
                ExitApp.setForeground(Color.WHITE);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(first_name)
                                .addComponent(last_name))
                            .addComponent(phone_number)
                            .addComponent(mail_user))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ln)
                            .addComponent(fn)
                            .addComponent(phone)
                            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(back_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitApp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(add_valid1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitApp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last_name))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(first_name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phone_number)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mail_user)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(add_valid1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_menuActionPerformed
        // TODO add your handling code here:
        App.main(null);
    }//GEN-LAST:event_back_menuActionPerformed

    private void add_valid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_valid1ActionPerformed
        // TODO add your handling code here:

        String lastName = ln.getText().trim();
        String firstName = fn.getText().trim();
        String phoneNumberStr = phone.getText().trim();
        String emailUser = email.getText().trim();

        // Vérifier si les champs sont vides
        if (lastName.isEmpty() || firstName.isEmpty() || phoneNumberStr.isEmpty() || emailUser.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Tous les champs sont obligatoires.", "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Vérifier que le lastName contient au maximum deux noms composés
        if (lastName.split("\\s+").length > 2) {
            javax.swing.JOptionPane.showMessageDialog(this, "Le nom ne peut contenir que deux noms composés.", "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Vérifier que le firstName contient au maximum trois prénoms composés
        if (firstName.split("\\s+").length > 3) {
            javax.swing.JOptionPane.showMessageDialog(this, "Le prénom ne peut contenir que trois prénoms composés.", "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Vérifier que le numéro de téléphone est un entier valide et contient au maximum 8 chiffres
        int phoneNumber;
        if (!phoneNumberStr.matches("\\d{8}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Le numéro de téléphone doit contenir 8 chiffres.", "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            phoneNumber = Integer.parseInt(phoneNumberStr);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Numéro de téléphone invalide.", "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Vérifier si l'adresse email est valide
        String emailRegex = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
        if (!Pattern.matches(emailRegex, emailUser)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Adresse email invalide.", "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Créer un objet Add_mod avec les données du formulaire
        Add_mod newContact = new Add_mod(0, firstName, lastName, phoneNumber, emailUser, java.time.LocalDate.now().toString());

        // Utiliser le contrôleur pour ajouter le contact
        if (controller.existsByPhoneNumber(phoneNumber)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ce numéro de téléphone est déjà utilisé.", "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
            controller.addContacts(newContact);
            javax.swing.JOptionPane.showMessageDialog(this, "Contact ajouté avec succès.", "Succès", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

        
        
    }//GEN-LAST:event_add_valid1ActionPerformed

    private void ExitAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitAppActionPerformed
        // TODO add your handling code here:
        quitApplication2();
    }//GEN-LAST:event_ExitAppActionPerformed

    private void quitApplication2() {
        // Show a dialog with Yes and No options
        int option = JOptionPane.showOptionDialog(
                null,
                "Voulez-vous réellement quitter l'application ?",
                "Confirmation",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new Object[]{"Oui", "Non"},
                "Non" // Default button option
        );

        // Handle user selection
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else if (option == JOptionPane.NO_OPTION) {
            // Return to the main menu
            return;
        } else {
            // Handle any unexpected option, though in this case it's unlikely
            JOptionPane.showMessageDialog(null,
                    "Erreur : choix non reconnu.",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Add_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitApp;
    private javax.swing.JButton add_valid1;
    private javax.swing.JButton back_menu;
    private javax.swing.JTextField email;
    private javax.swing.JLabel first_name;
    private javax.swing.JTextField fn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel last_name;
    private javax.swing.JTextField ln;
    private javax.swing.JLabel mail_user;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel phone_number;
    // End of variables declaration//GEN-END:variables
}
