/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Mod;

import java.awt.Color;
import App.App;
import List_mod.List_mod_ctrl;
import Mod.Mod_option.Mod_Em_view;
import Mod.Mod_option.Mod_Fn_view;
import Mod.Mod_option.Mod_Ln_view;
import Mod.Mod_option.Mod_Pn_view;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Ardenshley Nage
 */
public class Mod_view extends javax.swing.JFrame {

    private static Mod_ctrl modCtrl;
    private static final String HOST = "jdbc:mysql://localhost:3306/contact_manager";
    private static final String USER = "root";
    private static final String PASSWORD = "";
    private final String nom;
    private final String id;
    private final String prenom;
    private final String telephone;
    private final String email;

    /**
     * Creates new form Mod_view
     */
    public Mod_view(String nom, String prenom, String telephone, String email, String id) {
        modCtrl = new Mod_ctrl(HOST, USER, PASSWORD);
        this.nom = nom;  // Initialisation des attributs
        this.id = id;
        this.prenom = prenom;
        this.telephone = telephone;
        this.email = email;
        initComponents();
        updateDetails(nom, prenom, telephone, email);
    }

    public static void updateDetails(String nom, String prenom, String telephone, String email) {
        if (mod_ln != null) {
            mod_ln.setText("1- Nom : " + nom);
        }
        if (mod_fn != null) {
            mod_fn.setText("2- Prénom : " + prenom);
        }
        if (mod_pn != null) {
            mod_pn.setText("3- Numéro de téléphone : " + telephone);
        }
        if (mod_em != null) {
            mod_em.setText("4- Adresse E-mail : " + email);
        }

    }

    private void quitApplication4() {
        // Show a dialog with Yes and No options
        int option = JOptionPane.showOptionDialog(
                null,
                "Voulez-vous réellement quitter l'application ?",
                "Confirmation",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new Object[]{"Oui", "Non"},
                "Non"
        );

        // Handle user selection
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else if (option == JOptionPane.NO_OPTION) {
            // Return to the main menu
            return;
        } else {
            // Handle any unexpected option, though in this case it's unlikely
            JOptionPane.showMessageDialog(null,
                    "Erreur : choix non reconnu.",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void handleChoice(int choice) {
        switch (choice) {
            case 1 -> {
                Mod_Ln_view modLnView = new Mod_Ln_view(nom, id);
                modLnView.setVisible(true);
                System.out.println(id);
            }
            case 2 -> {
                Mod_Fn_view modFnView = new Mod_Fn_view(prenom, id);
                modFnView.setVisible(true);
            }
            case 3 -> {
                Mod_Pn_view modPnView = new Mod_Pn_view(telephone, id);
                modPnView.setVisible(true);
            }
            case 4 -> {
                Mod_Em_view modEmView = new Mod_Em_view(email, id);
                modEmView.setVisible(true);
            }
            default ->
                JOptionPane.showMessageDialog(this, "Choix invalide.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back_home = new javax.swing.JButton();
        ExitApp = new javax.swing.JButton();
        mod_ln = new javax.swing.JLabel();
        mod_fn = new javax.swing.JLabel();
        mod_pn = new javax.swing.JLabel();
        mod_em = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Élément à modfier");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));

        back_home.setBackground(new java.awt.Color(0, 0, 0));
        back_home.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        back_home.setForeground(new java.awt.Color(255, 255, 255));
        back_home.setText("Retour");
        back_home.setMaximumSize(new java.awt.Dimension(79, 33));
        back_home.setMinimumSize(new java.awt.Dimension(79, 33));
        back_home.setPreferredSize(new java.awt.Dimension(79, 33));
        back_home.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                back_home.setBackground(Color.WHITE);
                back_home.setForeground(Color.BLACK);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                back_home.setBackground(Color.BLACK);
                back_home.setForeground(Color.WHITE);
            }
        });
        back_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_homeActionPerformed(evt);
            }
        });

        ExitApp.setBackground(new java.awt.Color(0, 0, 0));
        ExitApp.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ExitApp.setForeground(new java.awt.Color(255, 255, 255));
        ExitApp.setText("Quitter");
        ExitApp.setMaximumSize(new java.awt.Dimension(79, 33));
        ExitApp.setMinimumSize(new java.awt.Dimension(79, 33));
        ExitApp.setPreferredSize(new java.awt.Dimension(79, 33));
        ExitApp.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                ExitApp.setBackground(Color.WHITE);
                ExitApp.setForeground(Color.BLACK);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                ExitApp.setBackground(Color.BLACK);
                ExitApp.setForeground(Color.WHITE);
            }
        });
        ExitApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitAppActionPerformed(evt);
            }
        });

        mod_ln.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        mod_ln.setForeground(new java.awt.Color(255, 255, 255));
        mod_ln.setText("1- Nom");
        mod_ln.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mod_ln.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                handleChoice(1);
            }
            @Override
            public void mouseEntered(MouseEvent e) {
                mod_ln.setForeground(Color.BLACK);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                mod_ln.setForeground(Color.WHITE);
            }
        });

        mod_fn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        mod_fn.setForeground(new java.awt.Color(255, 255, 255));
        mod_fn.setText("2- Prénom");
        mod_fn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mod_fn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                handleChoice(2);
            }
            @Override
            public void mouseEntered(MouseEvent e) {
                mod_fn.setForeground(Color.BLACK);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                mod_fn.setForeground(Color.WHITE);
            }
        });

        mod_pn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        mod_pn.setForeground(new java.awt.Color(255, 255, 255));
        mod_pn.setText("3- Numéro de téléphone");
        mod_pn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mod_pn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                handleChoice(3);
            }
            @Override
            public void mouseEntered(MouseEvent e) {
                mod_pn.setForeground(Color.BLACK);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                mod_pn.setForeground(Color.WHITE);
            }
        });

        mod_em.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        mod_em.setForeground(new java.awt.Color(255, 255, 255));
        mod_em.setText("4- Adresse E-mail");
        mod_em.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mod_em.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                handleChoice(4);
            }
            @Override
            public void mouseEntered(MouseEvent e) {
                mod_em.setForeground(Color.BLACK);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                mod_em.setForeground(Color.WHITE);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(201, 201, 201))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(back_home, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitApp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mod_em)
                    .addComponent(mod_pn)
                    .addComponent(mod_fn)
                    .addComponent(mod_ln))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(mod_ln)
                .addGap(18, 18, 18)
                .addComponent(mod_fn)
                .addGap(18, 18, 18)
                .addComponent(mod_pn)
                .addGap(18, 18, 18)
                .addComponent(mod_em)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_homeActionPerformed
        // TODO add your handling code here:
        App.main(null);
    }//GEN-LAST:event_back_homeActionPerformed

    private void ExitAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitAppActionPerformed
        // TODO add your handling code here:
        quitApplication4();
    }//GEN-LAST:event_ExitAppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mod_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mod_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mod_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mod_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mod_view("", "", "", "", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitApp;
    private javax.swing.JButton back_home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JLabel mod_em;
    private static javax.swing.JLabel mod_fn;
    private static javax.swing.JLabel mod_ln;
    private static javax.swing.JLabel mod_pn;
    // End of variables declaration//GEN-END:variables
}
